# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/acruxtech/Documents/study/bmstu_al/semester_1/labs/2024_11_16

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/acruxtech/Documents/study/bmstu_al/semester_1/labs/2024_11_16

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acruxtech/Documents/study/bmstu_al/semester_1/labs/2024_11_16/CMakeFiles /home/acruxtech/Documents/study/bmstu_al/semester_1/labs/2024_11_16//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acruxtech/Documents/study/bmstu_al/semester_1/labs/2024_11_16/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bmstu_al_lab_7

# Build rule for target.
bmstu_al_lab_7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bmstu_al_lab_7
.PHONY : bmstu_al_lab_7

# fast build rule for target.
bmstu_al_lab_7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/build
.PHONY : bmstu_al_lab_7/fast

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/task1.o: source/task1.cpp.o
.PHONY : source/task1.o

# target to build an object file
source/task1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task1.cpp.o
.PHONY : source/task1.cpp.o

source/task1.i: source/task1.cpp.i
.PHONY : source/task1.i

# target to preprocess a source file
source/task1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task1.cpp.i
.PHONY : source/task1.cpp.i

source/task1.s: source/task1.cpp.s
.PHONY : source/task1.s

# target to generate assembly for a file
source/task1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task1.cpp.s
.PHONY : source/task1.cpp.s

source/task2.o: source/task2.cpp.o
.PHONY : source/task2.o

# target to build an object file
source/task2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task2.cpp.o
.PHONY : source/task2.cpp.o

source/task2.i: source/task2.cpp.i
.PHONY : source/task2.i

# target to preprocess a source file
source/task2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task2.cpp.i
.PHONY : source/task2.cpp.i

source/task2.s: source/task2.cpp.s
.PHONY : source/task2.s

# target to generate assembly for a file
source/task2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmstu_al_lab_7.dir/build.make CMakeFiles/bmstu_al_lab_7.dir/source/task2.cpp.s
.PHONY : source/task2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bmstu_al_lab_7"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/task1.o"
	@echo "... source/task1.i"
	@echo "... source/task1.s"
	@echo "... source/task2.o"
	@echo "... source/task2.i"
	@echo "... source/task2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

